import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { GetBooks } from "../apis/books";
import BooksSec from "../components/BooksSec";
import Landing from "../components/Landing";

export default function Home() {
  const dispatch = useDispatch();
  const store = useSelector((store) => store);
  useEffect(() => {
    dispatch(GetBooks());
  }, []);
  useEffect(() => {
    console.log(store);
  }, [store]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
      <BooksSec />
    </div>
  );
}
